spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/techsolutions_sportcoach
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver